### ISSUE TITLE
Conflict with Token tooltip alt

### ISSUE THREAD

**Issue by uniwars** [theripper93/token-z#1]
Hi, I get a strange conflict between token-z and token tooltip alt :

Using PF2E System on Foundry V9, when both modules are enabled, token tooltip alt no longer works but only for actors coming from the bestiary
Here it works for a created NPC : 
![image](https://user-images.githubusercontent.com/65986545/148928860-bb1f616a-b07f-4546-8273-f2b6474f1c73.png)

Here it doesn't for a monster from the bestiary : 
![image](https://user-images.githubusercontent.com/65986545/148928992-8243909d-c0f7-42e5-8c50-19ec8cc55172.png)

**Comment by theripper93** [comment]
For some strange reason TTA uses token z index, I cannot do anything in my end, you’ll need to open a request in their side
