### ISSUE TITLE
Request - Allow Z button to swap selected tokens when one is at a higher evavation than each other

### ISSUE THREAD

**Issue by GorgoPrimus** [theripper93/token-z#11]
Not sure if this something you'd be open to handling as a feature for this module or not but... I know if one token is on top of another you can press Z to sort between them, but when one of them is at a higher height that doesn't seem to work. Is it possible to have the module enable you to still cycle/select a token at a lower elevation in the same square with Z?
I had to GM a fight with flying creatures/players going over and under each other today and it was a huge pain.

Thanks either way, cause this module has been amazingly helpful as is.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
