### ISSUE TITLE
Module does not function as of v10.290

### ISSUE THREAD

**Issue by GambetTV** [theripper93/token-z#3]
I'm using 0.7.6 of your module with Foundry v10.290, and as far as I can tell your module does not function any longer. Selecting a token does not increase it's Z-Order, going into the Token Configuration and manually changing the Z-Order doesn't do anything either. Z-Order is still a field in Token Configuration at least.

Disabling your module at least allows me to change token order temporarily by selecting tokens.

**Comment by theripper93** [comment]
should be fixed

**Comment by GambetTV** [comment]
Seems like the Manual Sorting is fixed, but selecting a token still doesn't change its weight. This is weird because if I disable your token, then selecting a token does change it's Z-Order. I've tried this with all modules turned off except yours, even with brand new tokens just to make sure there wasn't anything funny going on with them. It doesn't fix it.

**Comment by theripper93** [comment]
Its working on my end, it makes me think that your system is doing something strange. What system are you using

**Comment by GambetTV** [comment]
DnD5e, the most up to date version, same with Foundry.
