### ISSUE TITLE
BUG: Selecting Tokens doesn't give them a +1 z-index unless you're moving them

### ISSUE THREAD

**Issue by GambetTV** [theripper93/token-z#4]
I'm using the latest version of Foundry 10 and DnD5e, with all my modules turned off except this one, and still getting the bug. I've installed a new game world with only your module and I'm still getting it.

The bug is: Have two tokens that slightly overlap. Single left click on the token beneath the other token. In past versions of Token Z this would cause the token to immediately move on top of the other, as long as they were both the same size and had the same Z-Index. This no longer happens. Now the only way to get this to work is to actually drag the token a bit. Even dragging the token 1 pixel tends to work, but isn't the way it should work as far as I know.

EDIT: It should be noted that with your module turned off, it works perfectly. So it definitely seems to be your module causing it to not work.

**Comment by theripper93** [comment]
This is due to a core bug i'm pretty sure, i've implemented a workaround for now that it should fix the issue. Let me know if it's solved
