### ISSUE TITLE
BUG: Pressing Z to send to back not updating the scene

### ISSUE THREAD

**Issue by cs96and** [theripper93/token-z#7]
When you press Z to send a token to the back, the scene does not update, and the token doesn't move to the back.  It looks like when you [merged my changes](https://github.com/theripper93/token-z/pull/5/), you missed out the following crucial line...

```javascript
canvas.tokens.objects.sortDirty = canvas.primary.sortDirty = true;
```

![image](https://user-images.githubusercontent.com/898086/214081449-5c13c737-2277-4b89-9430-573aa2ae6e1a.png)

**Comment by MxViolette** [comment]
I'm not sure if this is best placed as a comment here, or if a separate issue needs to be opened.

With only Token Z selected for Active Modules, it is still not behaving as expected for Tokens. While pressing 'z' does move the image behind another image in the same stack, the cursor still selects the background Token. Auto Sorting does not apply, and neither does Manual Sorting. Changing the value of the Z-Index Offset does not seem to affect the Token.

**Comment by cs96and** [comment]
@MxViolette yes it's the same bug.  I saw the same thing happening too

**Comment by theripper93** [comment]
Sorry everyone, I totally forgot to adjust this, that’s why I tend to push people to open issues on discord haha, should be sorted, pun intended
